version: '3.8'
services:
  db:
    image: mariadb:11.0.2
    container_name: "mariadb_docker"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "password123"
      MYSQL_DATABASE: "googlemap_dev"
      TZ: "Australia/Melbourne"
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mariadb:
    driver: local
