export const LOCATION = {
    LOAD_RESOURCES:      "LOCATION_LOAD_RESOURCES",
    RECEIVE_RESOURCES:   "LOCATION_RECEIVE_RESOURCES",
    SELECT_RESOURCE:     "LOCATION_SELECT_RESOURCE",
    FILTERING_RESOURCE:  "LOCATION_FILTERING_RESOURCE"
}
